app/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout')
]

app/articles/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from  . import views


urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^test$', views.article_list),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_details, name="detail")
]

app/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage),
]

# static files
urlpatterns += staticfiles_urlpatterns()
# media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models

# Create your models here.

app/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # add in thumbnail and author
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    # check if is request POST
    if request.method == 'POST':
        # access to all the form data
        form = UserCreationForm(request.POST)
        # validate form data
        if form.is_valid():
            # save data in db
            user = form.save()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            return redirect('list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

app/articles/views.py
from django.shortcuts import render

from django.shortcuts import  render
from .models import Article
from django.contrib.auth.decorators import login_required


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="accounts:login")
def article_create(request):
    return render(request, 'articles/article_create.html')

app/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import  render


def homepage(request):
    #return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

app/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}

        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" >
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

app/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

app/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{%block content%}
    <div class="create-article">

            <h2>Create a article</h2>

    </div>
{% endblock %}

app/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{%block content%}
    <div class="article_detail">
        <div class="article">
            <h2>{{ article.title }}</a></h2>
            <img src="{{ article.thumb.url }}" alt="">
            <p>
                {{ article.body }}
            </p>
            <p>
                {{ article.date }}
            </p>
        </div>
    </div>
{% endblock %}

app/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{%block content%}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>
                    {{ article.snippet }}
                </p>
                <p>
                    {{ article.date }}
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <p>this is us.</p>
</body>
</html>

app/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'list' %}"><img src="{% static 'logo.png' %}" alt=""></a></h1>
        <nav style="display:flex; justify-content:end">
            <ul>
                <li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock%}
    </div>
</body>
</html>

app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to djangonautic</p>
</body>
</html>